### ISSUE TITLE
Modularize the library

### ISSUE THREAD

**Issue by robinmatz** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#101]
This one, I have been thinking about a while.

The current library structure looks like this
```
.
├── Mainframe3270
│   ├── __init__.py
│   ├── py3270.py
│   ├── version.py
│   └── x3270.py
```

where the library keywords are mainly in `x3270.py`. With new features coming in, x3270.py will eventually grow quite big, which makes it hard to maintain.

My suggestion would be to split the library keywords across multiple files, each of them grouping together keywords according to their functionality.

The test modules under utest/x3270 already suggest one way of how keywords might be grouped together
```
utest/x3270/
...
├── test_assertions.py
├── test_commands.py
├── test_connection.py
...
├── test_read.py
├── test_screenshot.py
├── test_wait_and_timeout.py
└── test_write.py
```
i.e. assertions, commands, read, screenshot, wait, write.

**Comment by Harm10** [comment]
Splitting seems like a good idea but not too much otherwise you are missing the overview.
