### ISSUE TITLE
Missing `Mainframe3270/keywords/*.py` in manifest file `robotframework_mainframe3270.egg-info/SOURCES.txt`

### ISSUE THREAD

**Issue by ericleoo** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#106]
Can't import `Mainframe3270` due to `Mainframe3270/keywords/*.py` missing in manifest file `robotframework_mainframe3270.egg-info/SOURCES.txt`
```
PS C:\Users\user\Project> .\.venv\Scripts\python.exe
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import Mainframe3270
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\Project\.venv\Lib\site-packages\Mainframe3270\__init__.py", line 11, in <module>
    from Mainframe3270.keywords import (AssertionKeywords, CommandKeywords,
ModuleNotFoundError: No module named 'Mainframe3270.keywords'
>>>
```

**Comment by samuelpcabral** [comment]
@robinmatz if you have some time, plase take a look on this, should be related with the recent split files. =)

**Comment by ericleoo** [comment]
Yes.. It's not obtained from pypi.. I tried installing right from the repo using `pip install git+https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library.git` as I wanted to try the latest commits (i.e. commit `ef13bf6` to enable concurrent sessions for wc3270) that are not yet published..

**Comment by robinmatz** [comment]
Ahh, I understand. There is still one PR open, that we originally wanted to include in the new 4.0 release. Is it ok for you to wait until the next release?

In the meantime, what you can do is to clone the repository and to change this line in setup.py
```
diff --git a/setup.py b/setup.py
index 26edce9..239c2e2 100644
--- a/setup.py
+++ b/setup.py
@@ -27,7 +27,7 @@ package_kwargs = {
     "license": "MIT License",
     "license_files": ["LICENSE.md", "THIRD-PARTY-NOTICES.txt"],
     "url": "https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library",
-    "packages": ["Mainframe3270"],
+    "packages": ["Mainframe3270", "Mainframe3270.keywords"],
     "install_requires": ["robotframework", "robotframework-pythonlibcore"],
     "classifiers": [
         "Development Status :: 5 - Production/Stable",
```

Then, open a command line prompt in the cloned repository and run

```
pip install wheel
pip install ./
```

Let me know if this helps.

**Comment by ericleoo** [comment]
Sure. Thank you!
