### ISSUE TITLE
Commands with cursor position?

### ISSUE THREAD

**Issue by Harm10** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#109]
Hi!
I would like to have some commands that either return the x/ypos of the current cursor position (e.g. after Move Next/Previous Field) or use the current cursor position (e.g. Read with only length specified).
Also helpful would be something like Search Screen with a string returning the x/ypos.

Could this be added to the library?

**Comment by robinmatz** [comment]
So at least for the first addition, to get the cursor position, there is no x3270 action that would return that value.

As for the second one, to Read from the current position, it seems like this is an easy one. The Ascii() action provided by x3270 allows for reading the length of a string from the current cursor position if only one argument is specified.

About the last one, I have not yet come up with an idea.

**Comment by Harm10** [comment]
@robinmatz I looked at the commands too and was quite astonished that there does not seem to exist any command that returns the cursor position. Very weird.
Could it be reported at x3270 project as an enhancement?

Will reading at cursor position be an extension of the Read command or become a new command like Read_at_cursor?

If you have something for getting the cursor position then I would imagine using it in Search would be obvious?

**Comment by Harm10** [comment]
@robinmatz  I found this [http://x3270.bgp.nu/Unix/x3270-script.html](url) which describes the Status Format of 12 fields of which fields 9 and 10 are the cursor row and column. Could this of use?

**Comment by Harm10** [comment]
@robinmatz As you rightfully separated issues from this one, will this one be continued as only read from cursor position request?
(I guess Search screen could wait until there is a working Cursor query?)
Or should I create new issues for that and close this one?

**Comment by robinmatz** [comment]
Hey @Harm10 , you can create issues for the remaining features. I only created the first one, because this was the first that I wanted to work on.

**Comment by Harm10** [comment]
@robinmatz I have created 2 new issues for the other requests. So this one can be closed?

**Comment by Harm10** [comment]
@robinmatz Gentle reminder on my question.......... :-)

**Comment by robinmatz** [comment]
Ohh, sorry for the late reply. Yes, this issue can be closed now.

**Comment by Harm10** [comment]
Closed because issues were separated into different issue reports.

**Comment by Harm10** [comment]
@robinmatz Rereading this discussion I noticed we did not continue on my request for a command like Move to next field. I never created a separate issue for this. Should I do that still?

**Comment by Harm10** [comment]
Reopened this one to become more viewable for my question on Move to next field.

**Comment by robinmatz** [comment]
Hey @Harm10 , can you please explain what you wanted to change about the Move Next Field keyword?

A PR with a keyword to get the current cursor position has already been merged.

**Comment by Harm10** [comment]
@robinmatz If you have a screen with different input fields it would be easy to just move from field to field in stead of using it's exact position.
Also if you have a screen that contains a list of which you do not know how many lines it has it would be easy if you could move vertically if there is some field.

I understand that what I call field could be different things (input field, text field etc.).

In my view if you have already have a command that gives you the current cursor position then you can move horizontally and/or vertically so many positions would help a lot. Maybe that is the easiest first implementation?
And call it Move left/right/up/down?

Maybe you can tell me what you can discern of the type of field? If this is difficult then move to next input field would probably undoable.

Does this make sense?

**Comment by robinmatz** [comment]
I am not quite sure if I understand correctly. The library already offers two keywords, `Move Next Field` and `Move Previous Field`, to move between fields. Move Next Field leverages the underlying x3270 [Tab() action](https://x3270.miraheze.org/wiki/Tab()_action), moving to the next modifiable input field. Move Previous Field uses x3270's [BackTab() action](https://x3270.miraheze.org/wiki/BackTab()_action).

Do these keywords serve your use case?

**Comment by Harm10** [comment]
@robinmatz You are quite right to point to Move Next Field. This moves to the next INPUT field. But processing screens also gets information from other fields or locations on the screen. I do not know the correct terminology but a non input or text field is not reachable by this command.
Also navigating on the screen vertically is out of the question.
Now there is a command that gives you the Cursor position on the screen it seems to me that you can easily use that in a new command like Move Up or Move Down? If you understand what I mean with this I assume you will also understand Move Left and Move Right?

**Comment by robinmatz** [comment]
I was thinking about a keyword like
```robotframework
Move Cursor To     ypos=1     xpos=5
```
because it would be rather easy to implement. This keyword would allow you to move to any given ypos/xpos coordinate on the screen.

Does this sound good to you?

**Comment by Harm10** [comment]
Good idea!

**Comment by samuelpcabral** [comment]
Publised in version 4.1
