### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa6 in position 45: invalid start byte

### ISSUE THREAD

**Issue by raka2407** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#11]
Hi, keywords with strings as argument fails with UnicodeDecodeError: 'utf8' codec can't decode byte 0xa6 in position 45: invalid start byte. This happens on Python 2.x and 3.x versions. Keywords that fail : Page Should Contain, Wait Until String

**Comment by michael-j-morgan** [comment]
Could you share the solution you found?
