### ISSUE TITLE
Read at cursor position

### ISSUE THREAD

**Issue by Harm10** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#111]
I would like to have a command that reads just at the cursor position. So something similar as the current READ command but without the x/ypos.

**Comment by Harm10** [comment]
@robinmatz Just a question: do you expect me to have a look at your PR's on my Issues?

**Comment by robinmatz** [comment]
Hey @Harm10 , I do not expect you to, however, if you have any suggestions, I would be happy to hear them.

In any case, #111, is the last open PR. When all are merged, we can release a new version including the keywords that you suggested we add to the library.
