### ISSUE TITLE
Issue with Write Commands

### ISSUE THREAD

**Issue by vishalchaturvedi50** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#119]
Hi Team 

For my mainframe script I am facing an issue where for a particular field I am not able to enter alphanumeric value (ex: ABCDE2) through Write Bare, Write at position etc commands however for the same field I am able to enter the alphanumeric values manually. 

Further, if I try to put just numeric values ( Ex: 12345) I am able to enter that through automation seamlessly. 

Also, I am able to edit other fields with alphanumeric values seamlessly on the same screen through script without any issues. Can you please help me with what can be the issue in this scenario.

**Comment by samuelpcabral** [comment]
Hi @vishalchaturvedi50 I never see this before, but the library just send the command to the application (x3270, wc3270) so... if you can send the alphanumeric through the application it sould work in robot framework.

do you have more information? what is the application that you are using? (x3270, wc3270, s3270)
what is your OS? (linux, windows)

**Comment by samuelpcabral** [comment]
Hello @vishalchaturvedi50 still with the error? can you shre more info? Otherwise I will close this issue....
Thank You
