### ISSUE TITLE
Unable to write and enter after successful open connection_wc3270 emulator

### ISSUE THREAD

**Issue by vingithub123** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#12]
Hi,

i'm using wc3270 emulator and Mainframe3270 api with python robot framework. I'm just write a simple program to open wc3270 emulator, connect to server using ip address and port, and after that entering 3 letter text and hitting enter and trying to reach login page. 

I'm able to connect to server using statement, Open Connection    xxx.xxx.xx:xx:port, after that i need to enter 3 letter word on current cursor position and hit enter key to reach to login page, however it is not happening. Below is code i'm using:-

Library           Mainframe3270

*** Test Cases ***
Example
    Open Connection    xxx.xxx.xx:xx:port
    Write Bare    text
    Send Enter

After, executing above code, emulator screen shows, invalid text entered. However, i'm successfully able to reach to login page, when i'm doing above steps manually on wc3270 emulator.

Please suggest.

**Comment by samuelpcabral** [comment]
Sometimes the Robot Framework's speed is so high that we need to slow down after writing some text and before sending enter (maybe half a second is enough).

if after the mainframe opens, exist a input field, use the keyword "Wait Field Detected"

Try this:

```
*** Settings ***
Library         Mainframe3270

*** Test Cases ***
Example
    Open Connection    xxx.xxx.xxx.xxx    port=xx
    Change Wait Time After Write    0.5
    Change Wait Time    0.5
    Wait Field Detected
    Write Bare    text
    Send Enter
```

**Comment by vingithub123** [comment]
Thank you!, Change 'Wait Time After Write    5' and 'Wait Field Detected' statements have done the trick for me.
