### ISSUE TITLE
Wait field detected Issue 

### ISSUE THREAD

**Issue by FWDQK** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#121]
![wait field detected issue](https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/assets/111964982/2336c18b-1880-4e41-98ed-032c15899fe7)

Hi Team,
Incase if Mainframe application is down, the cursor is not detected.
Due to Wait field detected Keyword, it gets stuck at this point and does not close the window and go to next line of code, till we hit enter manually on this page.

Please suggest the solution for this issue.

**Comment by FWDQK** [comment]
Hi,
Any suggestion here, how can this be handled if app is down and this is triggered.
Flow gets stuck at this page, due to Wait field detected keyword and case status does not get updated as fail.

**Comment by samuelpcabral** [comment]
Hi @FWDQK Could you share the part of the code in RobotFramework where the problem occurs? from the beginning of the keyword until a little after the Wait field detected Keyword, just to understand the sequence of events. Thanks

**Comment by FWDQK** [comment]
> Hi @FWDQK Could you share the part of the code in RobotFramework where the problem occurs? from the beginning of the keyword until a little after the Wait field detected Keyword, just to understand the sequence of events. Thanks

So, we are trying Open Connection with Mainframe and then calling Wait Field Detected keyword, so that login page gets populated.
But if application is down, it shows the page (image is shared above). So as not fields is loaded, code gets stuck here.

**Comment by samuelpcabral** [comment]
I understand, we have no control over Wait Field Detected, because it is a function that already comes from the x3270.

So why don't you change the test logic? After opening the connection, look for something on the Mainframe to make sure it is up.

Look for a string from the first screen or something like that. only after this step works then use Wait Field Detected
