### ISSUE TITLE
For Mainframe application, we need to automate System i-Navigator of IBM AS400 application

### ISSUE THREAD

**Issue by FWDQK** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#122]
Hi,
Need your help and suggestion on how to automate the below:
For Mainframe application, we need to automate System i-Navigator of IBM AS400 application using RobotFramework.

**Comment by samuelpcabral** [comment]
Sorry, System i-Navigator it is not in our scope. Try looking if anyone has already made a python library for it.
