### ISSUE TITLE
How to send page up page down to terminal

### ISSUE THREAD

**Issue by jhachandan1994** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#125]
I need to send pageup/pagedown to the terminal how can i send these keys. pf7/pf8 is not working in my case.

**Comment by samuelpcabral** [comment]
Hi @jhachandan1994 You can use the Scroll action with the Execute Command keyword:
https://x3270.miraheze.org/wiki/Scroll()_action

In Robot Will be something link that:

```
Execute Command    Scroll(backward)  
Execute Command    Scroll(forward)
```

I will take advantage of your question and we will release a new version to update this information in the documentation for that keyword.
