### ISSUE TITLE
Does Mainframe3270 library supports IBM Access Client Solution app

### ISSUE THREAD

**Issue by FWDQK** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#127]
Hi Team,

We are able to access wc3270 for application which is working on pcsws.exe (AS400).
But the application which is configured in IBM Access Client Solution app (992 port, protocol : Telnet - TLS/SSL), we are getting Disconnected error.

Please help to suggest if wc3270 supports this. If yes, how to add it.

**Comment by samuelpcabral** [comment]
Sorry, I have no ideia, check the x3270 website http://x3270.bgp.nu/
