### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'maximize'

### ISSUE THREAD

**Issue by FWDQK** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#131]
Hi Team,
When we are trying to execute Mainframe application using RobotFramework and scehduling for night run, it throws below error:

Setup failed:
AttributeError: 'NoneType' object has no attribute 'maximize'

Please help to suggest the solution. Log.html is not created for the same.

**Comment by samuelpcabral** [comment]
Hi @FWDQK we don´t have any keyword with 'maximize', so is something else not related with the library,
