### ISSUE TITLE
AM not able to send/press functional keys to Mainframe screen .

### ISSUE THREAD

**Issue by rakesh-art** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#20]
Eg : I need to press functional keys F3,F4,f5 etc..  for main fram screen . was using command "Send F3" but its not working . please provide solution

**Comment by codecube** [comment]
Hi,

You need to use the Send PF keyword.
https://raw.githack.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/master/doc/Mainframe3270.html


In your case you should do: Send PF      3

Best Regards,
Pedro Costa

**Comment by rakesh-art** [comment]
We used this but its not working for us(Share sample code if you have any). 
could you please help us other alternative. can we do this with "Execute Command" option. if so can send us some sample examples with syntax.

**Comment by samuelpcabral** [comment]
@rakesh-art please see the file mainframe.robot inside folder tests: https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/blob/master/tests/mainframe.robot

line 189:
send PF    12

**Comment by rakesh-art** [comment]
Thanks for your prompt responce, we are already following this test file and "To press F3 we are writing code : "send PF 3"  but its not working .  Its giving error  : functional key not allowed , find the below screen 

![image](https://user-images.githubusercontent.com/62131858/76618584-f4f87700-654e-11ea-8991-b74b1f56ed00.png)

**Comment by samuelpcabral** [comment]
Hi, it appears to be something or some property of the mainframe itself. What the library does is it sends the x3270 commands. So if you open your mainframe inside the x3270 application: http://x3270.bgp.nu/ and F3 works, it should also work in the Robot Framework.

As we only have access to a public mainframe, https://www.pub400.com/ we were only able to test the library on this mainframe and here it continues to function normally.

In the meantime you can try the following keywork:
https://raw.githack.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/master/doc/Mainframe3270.html#Execute%20Command

Like this:
`Execute Command    PF(3)`

But as you can see in the Keyword code it will probably have the same result.

another point that you can test, as seen in line 133 of the x3270.py file, all commands are converted to utf-8 before being sent to the mainframe. If for some reason your mainframe does not support this encode, there may be a failure. If this is the case try to change the encode format and let us know if it works.

we can make the encode as a keyword argument.

Thanks.
