### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa6 in position 14: invalid start byte

### ISSUE THREAD

**Issue by michael-j-morgan** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#23]
As much as I'd rather not reopen a closed issue, I didn't see a resolution. 

I'm receiving the following error on Windows 10 x64 Build 17134.1726: 
KEYWORD Mainframe3270 . Page Should Contain All Strings ${list_strings}
FAIL | UnicodeDecodeError: 'utf8' codec can't decode byte 0xa6 in position 14: invalid start byte
-- | --

on either Python2.7 and Python3.7 with either one keyword or multiple.
My only success has been through WSL.

**Comment by samuelpcabral** [comment]
Hi @michael-j-morgan in the library we just compare the strings in python with utf8, if you are with decode error, try convert the string before using the keyword, try the .decode python function.
https://docs.python.org/3/howto/unicode.html#the-unicode-type

**Comment by michael-j-morgan** [comment]
Thank you @samuelpcabral, I really love this library. By changing py32070.py from line 446: return cmd.data[0].decode("utf-8")
to return cmd.data[0].decode("latin-1") did the trick!
