### ISSUE TITLE
Port specified without LU name then port is not used

### ISSUE THREAD

**Issue by Harm10** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#24]
I am test driving this package on using wc3270. In Robot I specify the port but the LU is not set.
Then the port does not get processed in the Open Connection.
If I change the code to
`#self.credential = self.host

self.credential = "%s:%s" % (self.host, self.port)`
it works fine.
Could you please change the code to also use the specified port when set?

**Comment by samuelpcabral** [comment]
Hi @Harm10 this code already exist in the Open Connection keyword, in line #61
https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/blob/master/Mainframe3270/x3270.py
do you need to change another code?

thanks.

**Comment by Harm10** [comment]
I have installed with pip and version is 2.8 then according to version.py. But that line after pip install is definitely like I specified: self.credential = self.host.
Does pip pick up a wrong version?

**Comment by samuelpcabral** [comment]
You're right, thanks for the warning. As soon as possible, we will generate a patch version for the installation by pip --upgrade
