### ISSUE TITLE
How to enter transaction code on CICS "sign-on is complete" screen?

### ISSUE THREAD

**Issue by Harm10** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#26]
I am able to connect and sign in on a CICS. Then I am trying to write the desired transaction code on that screen. That screen has no fields and no tabbable positions. Even when writing to pos 1,1 I get error: CommandError: No input field
How can I enter the transaction code?

**Comment by samuelpcabral** [comment]
What the library does is send commands to the x3270 emulator (http://x3270.bgp.nu/) so if you can write using the x3230 emulator, just replicate the same steps in the library. If the x3270 emulator cannot write, then the library will not be able to write either.

**Comment by Harm10** [comment]
I do not understand. I am using wc3270 which is the windows version of x3270. Or not?
I can write on the logon screen itself so that works. The screen after that is a "one line screen" so perhaps that forces this error?

**Comment by Harm10** [comment]
I should add that if I start wc3270 also manually I can get to the same screen and then just normally type the transaction code. The screen that is presented by CICS does not contain fields and is not tabable. So how can the error No input field be suppressed for such screens?

**Comment by samuelpcabral** [comment]
I never try to do this before, so i dont know the behavior of the library in this context. I assume that this mainframe does not have open access. So it is complicated to test this behavior without being able to reproduce the issue. 
If you have any way to be able to access this mainframe, please contact me by email.  (samuel.cabral @ altran.com)

**Comment by Harm10** [comment]
I will send you a mail (the mainframe is not publicly accessible) with some screen examples and a description of a workaround I just found.

**Comment by Harm10** [comment]
Adding: it looks like a problem in X3270 software itself. Trying to reach the author of that.

**Comment by Harm10** [comment]
It turns out X3270 has an option to prefix the host to tell it that it is for example a CICS screen (prefix C:). If you connect using this prefix then the problem is gone!
