### ISSUE TITLE
Cannot access execution context on start-up of RIDE

### ISSUE THREAD

**Issue by Harm10** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#27]
I am now testing on a new set-up RIDE 1.7.4.2 on Python 3.7.9
Although the Open Connection normally works on start-up of RIDE error "Cannot access execution context" is thrown.
According to a similar message on someone else's package I found an explanation that could be of assistance:
"You are trying to reference BuiltIn() before the test starts. That is what is meant by the error Cannot access execution context: the test hasn't started so there is no execution context. Simply put, you cannot access methods of the BuiltIn library before the test runs."
Result is that the Library line remains red.
This does not happen on Python 2.7 and an older version of RIDE.

**Comment by samuelpcabral** [comment]
We will wait for RIDE 2.0 to test with python 3. running without RIDE, the library works.

**Comment by Harm10** [comment]
I might add that there is no plan date for RIDE 2.0 to be released. The Python 3.7 version I am using has no real problems with packages of other suppliers. So what is the technical problem here?
Are you aware of any date for the RIDE 2.0 release?

**Comment by samuelpcabral** [comment]
I am using Python 3.8.7, and with this version, the RIDE 1.7.4.2 doesn't even open. And running the Mainframe library test in cmd all tests pass.. so to me it seems to be a problem with RIDE and not with the Mainframe library.

Using the RIDE 2.0b1 (https://pypi.org/project/robotframework-ride/2.0b1/) everything is working normally.

**Comment by Harm10** [comment]
I needed to update Mainframe3270 as well to version 2.9. Now the error message disappeared!
So we will wait now...................

**Comment by samuelpcabral** [comment]
I have no intentions of maintaining compatibility on any issues with RIDE
