### ISSUE TITLE
Underscore not recognized on screen?

### ISSUE THREAD

**Issue by Harm10** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#28]
I am testing on PUB400.com and tried to recognize this string on the screen:
Welcome_to_PUB400.COM
and this failed.
When I read the value on that position I get
Welcome to PUB400.COM
so apparently the underscores are translated to spaces?
Is this expected behavior?

**Comment by samuelpcabral** [comment]
Only the undescore of the text "Welcome to PUB400.COM" don´t are get by the library, if you write a text with underscore, like "user_1" and read this positions, the "_" came with the readed text.

anyway I do some improvments in the read keyword, now will work with special characters, like: á, ë, ç, etc.

**Comment by Harm10** [comment]
I will test the new version. Shouldn't you wait with closing the issue after this test is successful?

**Comment by Harm10** [comment]
I tested with new version. Underscores are still not picked up. Is that what you are saying in your reply?
If I copy/paste the text from the emulator screen the underscores are normally there.
So should it be fixed in this version? If not then will you update documentation for the Read command?
(It seems that I cannot change the status of this issue to Open?)
