### ISSUE TITLE
Getting Error while running No such file or directory: 'x3270'

### ISSUE THREAD

**Issue by sayom88** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#36]
I am using MacBook Pro. 

I have installed the library **pip3 install robotframework-mainframe3270**. 

Then installed the x3270 project using the command **brew install x3270** 

Now while running the script, I am seeing the error **FileNotFoundError: [Errno 2] No such file or directory: 'x3270'**

Any help on how to fix this please. Tnx.

**Comment by samuelpcabral** [comment]
Hi @sayom88 I have never tested this library on mac, I don't know if there is any problem or if there is any configuration missing, sorry. You need to check it out yourself, and if there's any need to fix it, I'll be very happy to receive a merge request.

**Comment by sayom88** [comment]
Even i am new to this.. Do you know anyone @samuelpcabral whom i can connect on this?

**Comment by samuelpcabral** [comment]
Unfortunately not. I only tested in Windows and Ubuntu

**Comment by sayom88** [comment]
in Ubuntu, after installing x3270, did you set that in path?

**Comment by sayom88** [comment]
I just ran with log level as TRACE, got this error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Mainframe3270/x3270.py", line 65, in open_connection
    self.mf.connect(self.credential)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Mainframe3270/py3270.py", line 358, in connect
    self.exec_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Mainframe3270/py3270.py", line 307, in exec_command
    c.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Mainframe3270/py3270.py", line 78, in execute
    return self.handle_result(result.decode("utf-8"))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Mainframe3270/py3270.py", line 91, in handle_result
    raise ValueError('expected "ok" or "error" result, but received: {0}'.format(result))

**Comment by samuelpcabral** [comment]
No, only did the sudo apt get, like is described in the wiki page of the library: https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/wiki/Instalation

**Comment by sayom88** [comment]
> No, only did the sudo apt get, like is described in the wiki page of the library: https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/wiki/Instalation

i did the same same

**Comment by sayom88** [comment]
Can you please help with the error that i get

**Comment by samuelpcabral** [comment]
Don´t know, I see in your log you are using python 3.10. I never try to run in this version, could be a bug. But I don´t have time and machine to install python 3.10 to test right now... you can open a new issue with this TRACE log and with your enviroment data to see if someone can help

**Comment by sayom88** [comment]
where to open the issue?

**Comment by sayom88** [comment]
Hi @samuelpcabral  changed the python from 3.10 to 3.9, still getting the same error:

**Comment by samuelpcabral** [comment]
ok @sayom88 please open a new issue with this log and all the informations about your enviroment, then we can ask help.

**Comment by sayom88** [comment]
Hello @samuelpcabral created the new issue with the robot script and the error details. Tnx. Please have a look.
