### ISSUE TITLE
Unable to connect to x3270 terminal from Mac machine

### ISSUE THREAD

**Issue by sayom88** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#37]
Hello Team,

I am using python 3.9 in my Mac. Also sharing the robot script which I have created to launch the Mainframe x3270 application

[MF2.robot.zip](https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/files/7251131/MF2.robot.zip)

Getting the following error while running the robot script

File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Mainframe3270/x3270.py", line 65, in open_connection
self.mf.connect(self.credential)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Mainframe3270/py3270.py", line 358, in connect
self.exec_command(command)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Mainframe3270/py3270.py", line 307, in exec_command
c.execute()
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Mainframe3270/py3270.py", line 78, in execute
return self.handle_result(result.decode("utf-8"))
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Mainframe3270/py3270.py", line 91, in handle_result
raise ValueError('expected "ok" or "error" result, but received: {0}'.format(result))

**Comment by sayom88** [comment]
Just fyi, I am running Mocha TN3270 Lite on my Mac for this.

**Comment by emanlove** [comment]
I was trying to assist @sayom88 and it looks like Mocha TN3270 has a different executable name (not `x3270`) and different argument structure [[1](https://mochasoft.dk/tn3270param.htm)]. It also seems there are many different x3270 emulators under MacOS [[Here is one reference](https://petr-vacula.medium.com/how-to-connect-to-mainframe-from-your-mac-laptop-using-x3270-16243667478) that notes its executable is `c3270`]. Thus support for MacOS might complicate things a little...

**Comment by sayom88** [comment]
Hi @samuelpcabral can update on this issue please..

**Comment by sayom88** [comment]
Any progress on this please?

**Comment by sayom88** [comment]
Hello, I have now able to run the x3270 simulator on my Mac. Thanks.

**Comment by MichaelSeeburger** [comment]
@sayom88 Could you please explain how you get it working?

**Comment by vinnus8660** [comment]
Hi @sayom88, We are currently dealing with this issue. If you recall any details about how you resolved it, please explain. Thank you!

**Comment by MichaelSeeburger** [comment]
Hi @vinnus8660 ,
With the newest update we're able to use it on MacOS, if visible = False has been defined. 
You do not have a graphical interface but it is working. Kind regards Michael
