### ISSUE TITLE
Support x3270 ``-codepage`` argument

### ISSUE THREAD

**Issue by ghost** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#41]
Hi there!

Our system under test uses non-ASCII characters like ä, ö, ü, etc. With the current setup, these characters are displayed like |, {, etc. 

Having read the [x3270 docs on codepages](https://x3270.miraheze.org/wiki/Host_code_page), I learned that different charsets can be set using the ``-charset`` argument. The default, if unset is ``bracket``.

It would be nice to be able to set the charset argument on Library import as *optional* parameter, like

```
*** Settings ***
Library        Mainframe3270    charset=cp273
```

If unset, it should default to ``bracket``, as is the current behavior of x3270.

**Comment by robinmatz** [comment]
I am currently working on providing an additional argument called `argfile` to `Open Connection`.

`argfile` will be able to take in a file with [x3270 command line options](https://x3270.miraheze.org/wiki/Category:Command-line_options).

This would implicitly solve this issue as well as provide flexibility to provide other arguments.

I am currently writing unit tests.
