### ISSUE TITLE
Support to mainframe connection with SSL/TLS

### ISSUE THREAD

**Issue by mbnetobr** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#51]
Hi All,

How can I inform the `Open Connection` keyword to open an SSL connection?

**Comment by robinmatz** [comment]
Hi @mbnetobr ,

you can use it like:
```robot
Open Connection    Y:L:<yourhost.com>
```
`Y:` and `L:` are so called prefixes for x3270's connect action. See, https://x3270.miraheze.org/wiki/Host_name_syntax#Prefixes
They are, more precisely, TLS prefixes. https://x3270.miraheze.org/wiki/Category:TLS_prefixes

`L:` meaning that a TLS negotiation is done before opening the TELNET connection.
`Y:` means that you trust the host certificate (without verification).

If you want to verify the host certificate, there is a manual for that as well

https://x3270.miraheze.org/wiki/TLS:_Host_certificate_verification_failed:_Hostname_mismatch

**Comment by mbnetobr** [comment]
@robinmatz thanks for the help.
