### ISSUE TITLE
When will the x3270.py open_connection(extra_args) commit be released to pypi?

### ISSUE THREAD

**Issue by awha86** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#59]
I am very interested in the committed changes to https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/blob/bc034a75e5a29783de5b18520767b68302a7d330/Mainframe3270/x3270.py#L52 but I wonder when these changes will be released to pypi, presumably under a new release version? (perhaps @robinmatz)

Cheers, and thanks for an awesome project!

**Comment by samuelpcabral** [comment]
Hi @awha86 I will release a new version very soon! :) thanks!

**Comment by awha86** [comment]
Hi @samuelpcabral thank you for the quick reply - looking forward to it :)

**Comment by robinmatz** [comment]
> Hi @awha86 I will release a new version very soon! :) thanks!

@samuelpcabral , next version is going to be 3.0?

**Comment by samuelpcabral** [comment]
> @samuelpcabral , next version is going to be 3.0?

I think yes, we have a lot changes to call this a new major version :)

**Comment by samuelpcabral** [comment]
Hi @awha86 Version released on pypi. Plase run
pip install robotframework-mainframe3270==3.0

Thanks
