### ISSUE TITLE
Terminal reset while execution

### ISSUE THREAD

**Issue by MichaelSeeburger** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#71]
Hello there,

First, great work you put into this. It's a awesome addition to the robot framework.

Lately I did reset my laptop and insalled the newest versions of all python libraries.
And I got two issues while using the robot mainframe 3270 library.
When I execute it with visible = True then suddenly the processing stops and I get like a start screen for wc3270:

![image](https://user-images.githubusercontent.com/39369290/207625496-248bf41e-7318-4613-9782-69e4ac610418.png)

and secondly the terminal is really scrambled

![image](https://user-images.githubusercontent.com/39369290/207626831-cf97c31d-ed87-422a-b4c5-20d4130e9ea7.png)

Do you have any clues what I can do to resolve these issues?

Thank yo. Kind regards Michael

**Comment by robinmatz** [comment]
Hi @MichaelSeeburger ,

given the error occurred after the upgrade it would be interesting to know your current OS and version.

Then also what version of python are you using?

**Comment by samuelpcabral** [comment]
@MichaelSeeburger Maybe your terminal config? like the model number? see this: https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/wiki/Keyword-Tests

**Comment by MichaelSeeburger** [comment]
Hello @robinmatz,
I am on a windows 11 laptop and using python 3.10.9. 

Hi @samuelpcabral ,
Ok I will try that and post my results back =) 

Thank you both

**Comment by MichaelSeeburger** [comment]
As an update:
I tried to change the model number with using extra Args for Open Connection and it did not help.
I was reinstalling all different versions which were available here: https://x3270.miraheze.org/wiki/Downloads
But this did not resolve the issue either. I'm still looking into it.

**Comment by MichaelSeeburger** [comment]
I was able to resolve the scrambled terminal error!
I think this has something to do with Windows 11 rather then anything else.

First I created a testcase which basically just waited a long time after connecting to the TSO.
If you then press ALT+Spacebar a menu pops up where you can click on "Settings".
At the bottom there is the option to define the start size of the screen. 
I picked 24x80 and  this issue was gone. Now I am testing if I still get the reset issue.

**Comment by MichaelSeeburger** [comment]
I did test it with a larger test suite and there are no "terminal resets" anymore. =)
There is only one new "cosmetic" issue left. Anything what robot enters is shifted down 3 rows as you can see in my uploaded picture. For example my operid "My Opid" has been entered 3 rows below in a false row. The testcases still work and this is just a visual bug

![image](https://user-images.githubusercontent.com/39369290/209139495-1158a09b-3f36-4466-b65f-65ceb7cd394b.png)

**Comment by samuelpcabral** [comment]
Great! So I will close this issue, and keep with this information related with WIndows 11
