### ISSUE TITLE
Executing tests in Linux headlessly 

### ISSUE THREAD

**Issue by lkhan** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#72]
Hello!

First of all, thank you for creating this framework. I'm having issues executing the framework on a Debian Linux server host without X11.

Here is the error I'm receiving:
`ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name "/dev/null"', DisplayNameError('/dev/null'))`

Does anyone have any suggestions or ideas to resolve this?

Thank you!

**Comment by robinmatz** [comment]
Hi @lkhan 

can you provide a minimal robot script that reproduces the error?

**Comment by lkhan** [comment]
@robinmatz thank you for responding. I was able to solve the issue, it turns out we were missing xorg dependencies .
