### ISSUE TITLE
Focus on wc3270 window opened by RobotFramework

### ISSUE THREAD

**Issue by Jmateusribeiro** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#73]
Hi,

There is a way to Robot focus on the wc3270 window opened by the test? For Exemple, if I have a wc3270 window opened and run a test, Robot will open a window but will focus on the window that was already open.

Another thing, it is possible to run two wc3270 test on the same machine but in different sessions? How?

Thanks,
Jorge Ribeiro

**Comment by robinmatz** [comment]
Hi @Jmateusribeiro ,

both of your questions are related to sessions, a feature that does not currently exist in this library, but would be a nice addition.

I have already looked into developing such a feature, but currently I do not have the time to continue.

Would you be interested in developing this feature? Some famous libraries that support it would be RobotFramework Requests and Selenium library. Maybe you can get some inspiration from them.
