### ISSUE TITLE
Return file path from Take Screenshot

### ISSUE THREAD

**Issue by Harm10** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#77]
Would it be possible to return the file name generated by Take Screenshot?

**Comment by robinmatz** [comment]
@Harm10 yes, but this functionality would need to be implemented. This is relatively easy, however.

In x3270.py the function take_screenshot may just return the file path.

Now the question would be, should it just be the filename or the whole file path?

I think for most users having the whole path may provide the most flexibility.

**Comment by Harm10** [comment]
I think the whole file path would be the best choice.
If this is a simple change I can also create a PR for it?

**Comment by robinmatz** [comment]
Yes, it's a simple change as I outlined in my previous comment.

Your help would be greatly appreciated!

**Comment by Harm10** [comment]
@robinmatz I have created PR https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/pull/78 
Please review and merge if all is correct.

**Comment by robinmatz** [comment]
Closing this with #78
