### ISSUE TITLE
Extra_args open connection and wc3270

### ISSUE THREAD

**Issue by Harm10** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#80]
As soon as I add extra_args (either list or txt file) to my Open Connection I get Winerror 10061 and the connection is not build. 
If I leave out the extra_args the connection is set up properly. 
I use a combination of lu=, port= and extra_args on my Open Connection command and am on Windows.

After some experimenting I noticed specifying LU=${EMPTY} together with port and extra_args leads to this situation.
If you leave out LU and also specify the extra arguments as -title (in stead of --title like is suggested in the documentation) then some of them are picked up. As the available arguments for wc3270 are limited as compared to the x3270 set people should be made aware of that and the documentation should specify some arguments that are in both sets.

You can also specify the port number as an extra argument but this leads to incorrect processing if you only specify the extra_args and leave out the port= leading to it being defaulted in created credential.

I also have difficulties specifying the model. It looks like the __init__ of wc3270 within py3270.py always specifies model 2?

So a lot to investigate and potentially change?

@robinmatz Can you confirm that the documentation example of the arguments having 2 dashes in front is wrong? Of is this correct if you are not on Windows?

**Comment by robinmatz** [comment]
Sorry that I haven't had the time to look into this issue so far.

There are many points you are addressing.

1. You are correct about the documentation being faulty in that the x3270 command line options only use one hyphen.

2.

**Comment by Harm10** [comment]
As I am working on a PR for Open connection I will correct the one hyphen and make a suggestion for a more clearer hint.

Creating a Open from session sounds like a good idea. I have no idea how to use such a session file within the code so you have to do the first work. Of course I am willing to test.

**Comment by robinmatz** [comment]
I will investigate into this. Since I updated my previous comment just now, could you check again and possibly answer point 3?

**Comment by robinmatz** [comment]
@Harm10 do you think merging #84 will resolve this issue, so it can be closed?
Note that there is #31 that already addresses the model number.

**Comment by Harm10** [comment]
@robinmatz I think this one can be closed as long as you continue work in some way for the session read request?

**Comment by robinmatz** [comment]
@Harm10 I am closing this now because #84 was successfully merged. 

The option to open a connection from a session file will be continued in issue #76
