### ISSUE TITLE
Getting error "Library specification file was not generated for 'Mainframe3270' library" while adding python library in red.xml

### ISSUE THREAD

**Issue by RahulSharma19021996** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#9]
Getting error "Library specification file was not generated for 'Mainframe3270' library" while adding python library in red.xml

**Comment by samuelpcabral** [comment]
Import the Mainframe3270.xml file that is inside the Doc folder. than you can use the Auto complete function in RED. 
![libspec](https://user-images.githubusercontent.com/37876961/54351852-60f88480-4648-11e9-8f7a-40d6e9236ec6.png)
