### ISSUE TITLE
Unable to connect mainframe application using wc3270

### ISSUE THREAD

**Issue by FWDQK** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#95]
Hi Team,
While we are trying to connect mainframe application using robotframework scripts, we are getting an error :
no connection could be made because the target machine actively refused it.

We have tried below ways to connect the same:
Mainframe3270.Open.Connection IP
Mainframe3270.Open.Connection IP port=23
Telnet.Open.Connection ip
Telnet.Open.Connection ip port=23

We are able to connect manual using 'connect IP' successfully on same system.

**Comment by samuelpcabral** [comment]
Sorry @FWDQK I can't help, in all the tests and mainframes I have access to, the library is working perfectly. Check if you can open the connection with the Mainframe using the WC3270 session wizard, because what the library does is simply manipulate this application.

**Comment by FWDQK** [comment]
Yes, we have already checked that the Mainframe connection is working fine using WC3270 session, when tried to access manually.
But only while trying to access via Robotframework script, it fails.

We have tried to add trace also, but even trace is giving an error.

**Comment by samuelpcabral** [comment]
Try open a connection to the pub400.com as we have in the Suite Setup inside atest/mainframe.robot (https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/blob/v3.2/atest/mainframe.robot)

If works, you have some problem with your mainframe, If fails, you have some problem with the configurations (check the wiki)
https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/wiki/Instalation
